# H2 Database
spring.datasource.url=jdbc:h2:mem:beerdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,caches

# App Info
info.app.name=Beer Guide API
info.app.description=Guia de Cervejas Artesanais para o projeto Java Advanced
info.app.version=1.0.0